---
# tasks file for zz_app
- name: Install dependencies
  ansible.builtin.include_tasks:
    file: "./base_workflow/01_install_dependencies.yml"

- name: Download and Install my_app
  ansible.builtin.include_tasks:
    file: "./base_workflow/02_install_app.yml"

- name: Configure Environment
  ansible.builtin.include_tasks:
    file: "./base_workflow/03_configure_app.yml"
