---
- name: Install Dependency packages
  package:
    name:
      - acl
      - sudo
      - python3-pymysql
    state: present
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10
